# -*- coding: utf-8 -*-
"""M5-Assignment(Advanced Boosting Algorithm).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sSJnuZ26Z_Iqpj_bX2_G01CBejOCHgOT
"""

import numpy as np
import pandas as pd

from google.colab import files
files.upload()

df=pd.read_csv('/content/seeds.csv')

df

df.shape

df.info()

df.isnull().sum()

X=df.drop('Type',axis=1)
y=df.Type

from sklearn.model_selection import train_test_split,KFold,cross_val_score

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

cv=KFold(n_splits=5,shuffle=True)

from sklearn.ensemble import RandomForestClassifier

reg=RandomForestClassifier()

reg.fit(X_train,y_train)

from xgboost import XGBClassifier

model=XGBClassifier()

score=cross_val_score(model,X,y,scoring='accuracy',cv=cv)

print('Accuracy is: ',np.mean(score))